### ISSUE TITLE
这个组件跑在win2008 r2 iis7.5上报错

### ISSUE THREAD

**Issue by thefristloser** [tencentyun/tls-sig-api-cs#1]
网站和控制台程序跑这组件都报错：
`[CryptographicException: 出现了内部错误。
]
   System.Security.Cryptography.NCryptNative.ImportKey(SafeNCryptProviderHandle provider, Byte[] keyBlob, String format) +3912296
   System.Security.Cryptography.CngKey.Import(Byte[] keyBlob, CngKeyBlobFormat format, CngProvider provider) +239
   tencentyun.TLSSigAPI..ctor(Int32 sdkappid, String priKeyContent, String pubKeyContent) +120`
升级到 .NET Framework 4.6.2后，控制台程序运行成功。网站还是报上面的错。
iis配置的是 .NET Framework 是4.0 是没有问题的。重启服务器也不管用。
请问这个该怎么解决。

**Comment by thefristloser** [comment]
找到网站使用的应用程序池-->右击-->高级设置-->打开如下图-->在加载用户配置文件选择true
可以解决。
但是，这样改会影响其它模块。 有没有其它方案呢

**Comment by weijunyi** [comment]
有的，正在开发。

**Comment by weijunyi** [comment]
https://github.com/tencentyun/tls-sig-api-cs-cpp 可以尝试下这个。

**Comment by weijunyi** [comment]
这个项目新版已经把算法库进行了更换，不存在上述问题了。
